language: php

matrix:
  include:
    - php: 5.1
      dist: precise
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5.9
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4snapshot
      dist: xenial

script:
  - php test.php