language: php
php:
  - "7.2"
services:
  - docker

env:
  - PHP_VERSION=5.2
  - PHP_VERSION=5.3
  - PHP_VERSION=5.4
  - PHP_VERSION=5.5
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2

script:
  - docker build -t "benchmark/${PHP_VERSION}" "docker/${PHP_VERSION}"
  - docker run -v "`pwd`:/opt/src"
      -w "/opt/src"
      "benchmark/${PHP_VERSION}"
      php test.php