dist: xenial

php:
  - 7.4

before_install: true

install:
  - pecl install ssh2-1.2
  - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sudo useradd --create-home --base-dir /home "phpseclib"
  - echo "phpseclib:phpseclib" | sudo chpasswd

script:
  - composer require phpseclib/phpseclib:3.0.x-dev
  - php test.php