language: php

dist: xenial

php:
  - 7.4

before_install: true

install:
  - sudo apt-get update
  - sudo apt-get -y install libssh2-1 libssh2-1-dev
  - cd /tmp
  - wget https://pecl.php.net/get/ssh2-1.2.tgz
  - tar xvf ssh2-1.2.tgz
  - cd ssh2-1.2
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sudo useradd --create-home --base-dir /home "phpseclib"
  - echo "phpseclib:phpseclib" | sudo chpasswd
  - cd

script:
  - composer require phpseclib/phpseclib:3.0.x-dev
  - php test.php