language: php
php:
  - "7.0"
sudo: false
services:
  - docker

env:
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2

script:
  - docker build -t "benchmark/${PHP_VERSION}" "docker/${PHP_VERSION}"
  - docker run -v "`pwd`:/opt/src" \
      -w "/opt/src" \
      "benchmark/${PHP_VERSION}" \
      php test.php