language: php
services:
  - docker

script:
  - composer require phpseclib/phpseclib:3.0.x-dev
  - docker pull "terrafrost/php7.4"
  - docker run -v "`pwd`:/opt/src"
      -w "/opt/src"
      "terrafrost/php7.4"
      php test.php